name: wastesortapp
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.17

  # Cloudinary
  cloudinary_flutter: ^1.3.0
  cloudinary_url_gen: ^1.7.0

  # Firebase
  firebase_core: ^3.12.0
  firebase_auth: ^5.5.1
  firebase_database: ^11.3.3
  cloud_firestore: ^5.6.4

  google_fonts: ^6.2.1

  google_sign_in: ^6.3.0
  flutter_facebook_auth: ^7.1.1

  cached_network_image: ^3.3.0
  image_picker: ^1.1.2
  permission_handler: ^11.0.1
  camerawesome: ^2.0.0
  open_filex: ^4.7.0
  path_provider: ^2.0.0
  photo_manager: ^3.6.4

  dotted_border: ^2.0.0
  dropdown_button2: ^2.3.9
  intl: ^0.20.2
  country_picker: ^2.0.27
  table_calendar: ^3.2.0
  email_otp: ^3.0.2
  internet_connection_checker_plus: ^2.7.1
  provider: ^6.1.2
  visibility_detector: ^0.4.0+2
  animated_leaderboard: ^0.1.4
  flutter_animate: ^4.5.2
  rxdart: ^0.28.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  assets:
    - lib/assets/icons/
    - lib/assets/images/

  uses-material-design: true
