name: wastesortapp
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Cloudinary
  cloudinary_flutter: ^1.3.0
  cloudinary_url_gen: ^1.7.0
  image_picker: ^1.1.2

  # Firebase
  firebase_core: ^3.12.0
  firebase_auth: ^5.5.0
  firebase_database: ^11.3.3
  cloud_firestore: ^5.6.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: Nunito
      fonts:
        - asset: lib/assets/fonts/nunito.ttf
    - family: Domine
      fonts:
        - asset: lib/assets/fonts/domine.ttf
