name: wastesortapp
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.17

  # Cloudinary
  cloudinary_flutter: ^1.3.0
  cloudinary_url_gen: ^1.7.0

  # Firebase
  firebase_core: ^3.12.0
  firebase_auth: ^5.5.0
  firebase_database: ^11.3.3
  cloud_firestore: ^5.6.4

  google_fonts: ^6.2.1

  image_picker: ^1.1.2
  permission_handler: ^11.0.1
  camerawesome: ^2.0.0
  open_filex: ^4.7.0
  path_provider: ^2.0.0
  photo_manager: ^3.0.0

  dotted_border: ^2.0.0
  dropdown_button2: ^2.3.9

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  assets:
    - lib/assets/icons/
    - lib/assets/images/

  uses-material-design: true
